version: "3.9"

services:
  https-portal:
    image: steveltn/https-portal:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: |
        ${PROD_HOST} -> http://nginx
      STAGE: staging
    volumes:
      - ./https-portal/certs:/var/lib/https-portal
    depends_on:
      - frontend
      - backend
    networks:
      - proxy

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
    command: /bin/bash -c "envsubst '$${FPORT} $${BPORT}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - frontend
      - backend
    networks:
      - proxy
      - internal

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend
    expose:
      - ${FPORT}
    env_file:
      - .env.production
    environment:
      FPORT: ${FPORT}
      BPORT: ${BPORT}
      NEXT_PUBLIC_BACKEND_URL: "https://${PROD_HOST}"
    networks:
      - internal

  backend:
    build:
      context: ./backend
    expose:
      - ${BPORT}
    env_file:
      - .env.production
    environment:
      BPORT: ${BPORT}
    networks:
      - internal

networks:
  proxy:
    external: false
  internal:
    external: false
