version: "3.7"

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO}
      MINIO_ROOT_PASSWORD: ${MINIO}
    volumes:
      - ./.data/cdn/development:/data
    command: server /data
