version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ${FRONTEND_IMAGE}
    volumes:
      - ./frontend/:/usr/src/app
    depends_on:
      - backend
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${BACKEND_IMAGE}
    volumes:
      - ./backend/:/usr/src/app
    env_file:
      - .env
