version: "3.9"

services:
  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile.staging:/etc/caddy/Caddyfile
      - caddy_data_staging:/data
      - caddy_config_staging:/config
    environment:
      - BPORT=${BPORT}
      - FPORT=${FPORT}
    depends_on:
      - frontend
      - backend
    networks:
      - internal

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    expose:
      - ${FPORT}
    env_file:
      - .env.staging
    networks:
      - internal

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - "${BPORT}"
    env_file:
      - .env.staging
    depends_on:
      - mongo
      - minio
    networks:
      - internal

  mongo:
    image: mongo:latest
    container_name: mongo_staging
    expose:
      - "27017"
    volumes:
      - mongo_data_staging:/data/db
    networks:
      - internal

  minio:
    image: "minio/minio:latest"
    container_name: minio_staging
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: "${CDN_KEY}"
      MINIO_ROOT_PASSWORD: "${CDN_SECRET}"
    volumes:
      - "minio_data_staging:/data/minio"
    command: minio server /data/minio --console-address ":9090"
    networks:
      - internal

networks:
  proxy:
    external: false
  internal:
    external: false

volumes:
  minio_data_staging:
    driver: local
    driver_opts:
      type: none
      device: ./.local/minio/staging
      o: bind
  mongo_data_staging:
    driver: local
    driver_opts:
      type: none
      device: ./.local/mongo/staging
      o: bind
  caddy_data_staging:
    driver: local
  caddy_config_staging:
    driver: local
