version: "3.9"

services:
  https-portal:
    image: steveltn/https-portal:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: |
        ${HOST} -> http://frontend:${FRONTEND_PORT}
        ${HOST}/api -> http://backend:${BACKEND_PORT}
      STAGE: ${STAGE}
    volumes:
      - ./https-portal/certs:/var/lib/https-portal
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - .env

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env

networks:
  default:
    driver: bridge
