version: "3.9"

services:
  https-portal:
    image: steveltn/https-portal:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: |
        localhost -> http://nginx
      STAGE: local
    volumes:
      - ./https-portal/certs:/var/lib/https-portal
    depends_on:
      - frontend
      - backend
    networks:
      - proxy

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
    command: /bin/bash -c "export FRONTEND_PORT=3000 BACKEND_PORT=3001 && envsubst '$${FRONTEND_PORT} $${BACKEND_PORT}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - frontend
      - backend
    environment:
      - FRONTEND_PORT=3000
      - BACKEND_PORT=3001
    networks:
      - proxy
      - internal

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    expose:
      - "3000"
    env_file:
      - .env.staging
    environment:
      - FRONTEND_PORT=3000
      - BACKEND_PORT=3001
    networks:
      - internal

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "3001"
    env_file:
      - .env.staging
    environment:
      - FRONTEND_PORT=3000
      - BACKEND_PORT=3001
    networks:
      - internal

  minio:
    image: minio/minio
    container_name: minio
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data/minio/staging:/data
    command: server /data
    networks:
      - internal

networks:
  proxy:
    external: false
  internal:
    external: false
