version: "3.9"

services:
  https-portal:
    image: steveltn/https-portal:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: |
        localhost -> http://nginx
      STAGE: local
    volumes:
      - ./https-portal/certs:/var/lib/https-portal
    depends_on:
      - nginx
    networks:
      - proxy

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
    command: >
      /bin/bash -c "
      envsubst '\$${FPORT} \$${BPORT}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf &&
      nginx -g 'daemon off;'"
    depends_on:
      - frontend
      - backend
    environment:
      FPORT: ${FPORT}
      BPORT: ${BPORT}
    networks:
      - proxy
      - internal

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    expose:
      - ${FPORT}
    env_file:
      - .env.staging
    environment:
      FPORT: "${FPORT}"
      BPORT: "${BPORT}"
      NEXT_PUBLIC_BACKEND_URL: "https://localhost"
    networks:
      - internal

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "${BPORT}"
    env_file:
      - .env.staging
    depends_on:
      - mongo
      - minio
    environment:
      BPORT: ${BPORT}
      CDN_KEY: ${MINIO}
      CDN_SECRET: ${MINIO}
      CDN_REGION: sfo3
      CDN_BUCKET: ${MINIO}
      CDN_ENDPOINT: http://localhost:9000
      MONGODB_URI: mongodb://root:staging@mongo:27017/?authSource=admin
    networks:
      - internal

  mongo:
    image: mongo:latest
    container_name: mongodb
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: staging
    volumes:
      - mongo_data_staging:/data/db
    networks:
      - internal

  minio:
    image: "minio/minio:latest"
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: "${MINIO}"
      MINIO_ROOT_PASSWORD: "${MINIO}"
    volumes:
      - "minio_data_staging:/data/minio"
    command: minio server /data/minio --console-address ":9090"

networks:
  proxy:
    external: false
  internal:
    external: false

volumes:
  minio_data_staging:
    driver: local
    driver_opts:
      type: none
      device: ./.data/minio/staging
      o: bind
  mongo_data_staging:
    driver: local
    driver_opts:
      type: none
      device: ./.data/mongo/staging
      o: bind
