version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env.production
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/app
    ports:
      - "3001:3001"
    env_file:
      - .env.production
    restart: always

networks:
  default:
    driver: bridge
