version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=development
    expose:
      - "3000"

  backend:
    build: ./backend
    environment:
      - NODE_ENV=development
    expose:
      - "3001"

networks:
  default:
    driver: bridge
