version: "3.9"

services:
  https-portal:
    image: steveltn/https-portal:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      DOMAINS: |
        ${HOST} -> http://nginx
      STAGE: ${STAGE}
    volumes:
      - ./https-portal/certs:/var/lib/https-portal
    depends_on:
      - frontend
      - backend
    networks:
      - proxy

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template:ro
    command: /bin/bash -c "envsubst '$${FRONTEND_PORT} $${BACKEND_PORT}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - frontend
      - backend
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
      - BACKEND_PORT=${BACKEND_PORT}
    networks:
      - proxy
      - internal

  frontend:
    image: ${FRONTEND_IMAGE}:latest
    depends_on:
      - backend
    expose:
      - "${FRONTEND_PORT}"
    env_file:
      - .env
    networks:
      - internal

  backend:
    image: ${BACKEND_IMAGE}:latest
    expose:
      - "${BACKEND_PORT}"
    env_file:
      - .env
    networks:
      - internal

networks:
  proxy:
    external: false
  internal:
    external: false
