version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: livingmilehigh/frontend
    volumes:
      - ./frontend/:/usr/src/app
    depends_on:
      - backend
    env_file:
      - .env.production

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: livingmilehigh/backend
    volumes:
      - ./backend/:/usr/src/app
    env_file:
      - .env.production
