version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./frontend:/app/frontend
      - ./shared:/app/shared
    ports:
      - "3000:3000"
    env_file:
      - .env.${NODE_ENV}

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
    ports:
      - "3001:3001"
    env_file:
      - .env.${NODE_ENV}

networks:
  default:
    driver: bridge
