version: "3.9"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile:ro
      - caddy_data_prod:/data
      - caddy_config_prod:/config
    environment:
      FPORT: ${FPORT}
      BPORT: ${BPORT}
      HTTPS_CERT_EMAIL: ${HTTPS_CERT_EMAIL}
    depends_on:
      - frontend
      - backend
    networks:
      - internal

  frontend:
    image: ${DOCKERHUB_USERNAME}/frontend:latest
    container_name: frontend
    depends_on:
      - backend
    expose:
      - ${FPORT}
    env_file:
      - .env.production
    networks:
      - internal

  backend:
    image: ${DOCKERHUB_USERNAME}/backend:latest
    container_name: backend
    expose:
      - ${BPORT}
    env_file:
      - .env.production
    networks:
      - internal

networks:
  proxy:
    external: false
  internal:
    external: false

volumes:
  caddy_data_prod:
    driver: local
  caddy_config_prod:
    driver: local
