version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  frontend:
    image: livingmilehigh/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - .env.development
    restart: always

  backend:
    image: livingmilehigh/backend:latest
    ports:
      - "3001:3001"
    env_file:
      - .env.development
    restart: always

networks:
  default:
    driver: bridge
