services:
  frontend:
    build:
      context: ../frontend
    image: ${DOCKERHUB_USERNAME}/frontend:latest
    container_name: frontend
    depends_on:
      - backend
    env_file:
      - ../.env.production

  backend:
    build:
      context: ../backend
    image: ${DOCKERHUB_USERNAME}/backend:latest
    container_name: backend
    env_file:
      - ../.env.production
