services:
  minio:
    image: "minio/minio:latest"
    container_name: minio_dev
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: "${CDN_KEY}"
      MINIO_ROOT_PASSWORD: "${CDN_SECRET}"
    volumes:
      - "minio_data_dev:/data/minio"
    command: minio server /data/minio --console-address ":9090"

  mongo:
    image: mongo:latest
    container_name: mongo_dev
    ports:
      - "27017:27017"
    volumes:
      - "mongo_data_dev:/data/db"

volumes:
  mongo_data_dev:
    driver: local
  minio_data_dev:
    driver: local
