services:
  mongo:
    image: mongo:latest
    container_name: mongo_prod
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_PASSWORD}"
    volumes:
      - mongo_data_prod:/data/db

volumes:
  mongo_data_prod:
    driver: local
